
# This uses newer and faster docker based build system
sudo: false

language: php

notifications:
  on_success: never
  on_failure: change

php:
  - nightly
  - 7.4
  - 7.3

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0

matrix:
  allow_failures:
    - php: nightly

before_script:

  - bash tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION

script:
  - php -l plugin.php
  - phpunit