language: php

notifications:
  slack:
    if: (branch = master) OR (branch =~ /^(release).*$/)
    on_success: always
    on_failure: always

php:
  - nightly
  - 8.0
  - 7.4

jobs:
  allow_failures:
    - php: nightly

install:
  - rm composer.lock
  - travis_retry composer update --no-interaction --prefer-dist --no-suggest --no-progress

script:
  - composer test

cache:
  directories:
    - $HOME/.composer/cache
